print("& " * 15)
print("&                                    &")
print("&        哪来直接登顶的人生          &")
print("&        只有不断迭代的历程          &")
print("&                                    &")
print("& " * 15)
